[general]
    
    live_config_reload = false

[window]
    
    padding = { x = 10, y = 10 }
    decorations = "None"
    opacity = 0.8

[font]

    normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
    bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
    italic = { family = "JetBrains Mono Nerd Font", style = "Italic" }
    bold_italic = { family = "JetBrains Mono Nerd Font", style = "Bold Italic" }
    size = 14

[colors]

    # XTerm's default colors
    
    # Default colors
    [colors.primary]
    background = '#000000'
    foreground = '#ffffff'
    
    # Normal colors
    [colors.normal]
    black   = '#000000'
    red     = '#cd0000'
    green   = '#00cd00'
    yellow  = '#cdcd00'
    blue    = '#0000ee'
    magenta = '#cd00cd'
    cyan    = '#00cdcd'
    white   = '#e5e5e5'
    
    # Bright colors
    [colors.bright]
    black   = '#7f7f7f'
    red     = '#ff0000'
    green   = '#00ff00'
    yellow  = '#ffff00'
    blue    = '#5c5cff'
    magenta = '#ff00ff'
    cyan    = '#00ffff'
    white   = '#ffffff'

[cursor]

    style = { shape = "Beam", blinking = "On" }

[mouse]

    hide_when_typing = true
